# Generated by Django 3.1.1 on 2020-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipies/'),
        ),
    ]
